### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by markknol** [AustinEast/echo#3]
Hi there! Your website is down very often. 
Suggestion: Maybe you could host your content (demo/api) on GitHub pages?

**Comment by AustinEast** [comment]
Interesting.. The site and api are both hosted on Github Pages (I use the `gh-pages` branch for that). I haven't noticed any outages, but I also haven't been checking recently. If you see it down again, would you mind reporting any errors you see in your console/screenshots of what you see?

**Comment by markknol** [comment]
I still have this. It first loads very long time, then this is what I see. 

![image](https://user-images.githubusercontent.com/576184/56573770-1a406780-65c2-11e9-8d0d-01ae7a47a790.png)

**Comment by AustinEast** [comment]
Just had some time to look into it, and I haven't been able to reproduce the issue 😔

Im not sure what it could be, but there's a couple things you could try if you haven't already:
* Clear your cache
* Clear you *DNS* cache (It may have to do with the domain I added recently?)
* Ensure that you're appending `https://` to your URL
* If you've got a VPN running try disabling it

Sorry I can't provide more help, hopefully you can get it sorted!

**Comment by AustinEast** [comment]
Update: I found a weird DNS record for the domain and removed it. Let me know if this fixes it (it might take a day or so for the DNS change to propagate).

**Comment by markknol** [comment]
Seems to work now, thanks!
