### ISSUE TITLE
Possible issue colliding scaled bodies?

### ISSUE THREAD

**Issue by jobf** [AustinEast/echo#32]
I am trying to collide a rectangle body that grows in size.

To grow the rectangle I use `body.shape.scale_y`  and offset the `y` position so that the body appears to grow in height only (rather than what it is actually doing, growing in both directions from the center).

It looks like collision is based on the original size of the rectangle rather than the scaled, see the video. I would expect collision when the top of the vertical rectangle meets the horizontal  rectangle (as shown in the second video).

https://user-images.githubusercontent.com/22012032/158840512-53736bd3-cd48-4230-a095-2b660a481448.mp4

The following video shows the body colliding normally (with no scale applied).

https://user-images.githubusercontent.com/22012032/158840749-0ce962d1-66ee-4021-9bdf-28b572404d1b.mp4

I've attached the code I was using to debug this, which extends BaseState from the samples project so can easily be dropped into there to test after renaming to `GrowRectangle.hx`.

[GrowRectangle.hx.txt](https://github.com/AustinEast/echo/files/8287939/GrowRectangle.hx.txt)

**Comment by AustinEast** [comment]
Nice catch! Thankfully it looks like I've already fixed this a local commit I made a bit ago but never pushed 😅 (https://github.com/AustinEast/echo/commit/d8e3f0cf263d7db753c7fef744d009af89f6970d)

I just released version 4.2.0 of echo to haxelib with this fix - your sample is working with it on my end, but let me know if it works for you as well.

**Comment by jobf** [comment]
Thanks I've tested here and can confirm that is working as expected.

![image](https://user-images.githubusercontent.com/22012032/159131784-e462ad6f-81c4-4d62-8da7-30728e7e8225.png)
