### ISSUE TITLE
Enter and exit collision callbacks do not work

### ISSUE THREAD

**Issue by kostik1337** [AustinEast/echo#4]
I've tried linux and html5 builds, enter and exit callbacks are not called at all.

A brief investigation shown that echo.Listener.last_collisions is always the same object as echo.Listener.collisions, so condition
`listener.last_collisions.find((f) -> return f.a == c.a && f.b == c.b || f.a == c.b && f.b == c.a) == null`
in Collision.hx:118 and Collision.hx:128 is always false.

A possible fix is to revert commit 8c3b101429838233fb6e92424ed783df3a6f0523

**Comment by AustinEast** [comment]
Good catch! I went ahead and reverted the commit and ill make a new haxelib release shortly 👍
