### ISSUE TITLE
Samples do not show any rotation / angular forces / moment of inertia -- is that supported?

### ISSUE THREAD

**Issue by jcward** [AustinEast/echo#5]
None of the samples (nice job having samples!) showcase any rotation - they all show simple translation movement. It makes me wonder whether the engine supports rotational forces.

Gave the API a quick browse... there seem to be fields named "rotation" -- so I yes? If so, it'd be great if an example showed it.

**Comment by AustinEast** [comment]
Hey! Rotations are currently not implemented, so all of the fields referencing rotation are just placeholders at the moment. This is planned to be done once polygon shapes are implemented.

Just so you're aware - once body/shape rotations are in place, I'm not planning on incorporating angular forces to collision resolution. I'd like to keep the built-in library's separation logic very simple, and I figured box2D/nape provide better support for that (except for maybe when I start on echo 2.0 😉).

**Comment by jcward** [comment]
Thanks for the info!
